// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dV5nEuukcyd7W2zOQ4qWon7Rvj4fdFU',
    appId: '1:1030780444957:web:6be134eedfb5bf759281f4',
    messagingSenderId: '1030780444957',
    projectId: 'pawter-dgm96',
    authDomain: 'pawter-dgm96.firebaseapp.com',
    storageBucket: 'pawter-dgm96.firebasestorage.app',
    measurementId: 'G-FK6Z0DBH87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPay0ocgl0z8ClvgNg_x2OUXyzZS9LoFI',
    appId: '1:1030780444957:android:9c3138619440e57d9281f4',
    messagingSenderId: '1030780444957',
    projectId: 'pawter-dgm96',
    storageBucket: 'pawter-dgm96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHnSBLI2RyLvnk6HsqUklACWqb6nR8mD8',
    appId: '1:1030780444957:ios:19b28095ec305b999281f4',
    messagingSenderId: '1030780444957',
    projectId: 'pawter-dgm96',
    storageBucket: 'pawter-dgm96.firebasestorage.app',
    iosBundleId: 'com.example.pawter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHnSBLI2RyLvnk6HsqUklACWqb6nR8mD8',
    appId: '1:1030780444957:ios:19b28095ec305b999281f4',
    messagingSenderId: '1030780444957',
    projectId: 'pawter-dgm96',
    storageBucket: 'pawter-dgm96.firebasestorage.app',
    iosBundleId: 'com.example.pawter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-dV5nEuukcyd7W2zOQ4qWon7Rvj4fdFU',
    appId: '1:1030780444957:web:a76aca86bade84639281f4',
    messagingSenderId: '1030780444957',
    projectId: 'pawter-dgm96',
    authDomain: 'pawter-dgm96.firebaseapp.com',
    storageBucket: 'pawter-dgm96.firebasestorage.app',
    measurementId: 'G-QSJ32LM0LW',
  );
}
